version: '2.2'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: elasticsearch-1
    environment:
      - node.name=elasticsearch-1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-2
      - cluster.initial_master_nodes=elasticsearch-1,elasticsearch-2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - $PWD/elasticsearch/data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: elasticsearch-2
    environment:
      - node.name=elasticsearch-2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-1
      - cluster.initial_master_nodes=elasticsearch-1,elasticsearch-2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - $PWD/elasticsearch/data2:/usr/share/elasticsearch/data
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.12.1
    container_name: kibana-1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-1:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch-1:9200","http://elasticsearch-2:9200"]'
    networks:
      - elastic

#  logstash:
#    image: docker.elastic.co/logstash/logstash:7.12.1
#    container_name: logstash
#    environment:
#      ELASTICSEARCH_URL: http://elasticsearch-1:9200
#      ELASTICSEARCH_HOSTS: '["http://elasticsearch-1:9200","http://elasticsearch-2:9200"]'
#    networks:
#      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  elastic:
    driver: bridge